App\Entity\Categoria:
  attributes:
    id:
      groups: ['get_categorias', 'get_restaurante', 'filtered']

    categoria:
      groups: ['get_categorias', 'create_categorias', 'get_restaurante', 'filtered']