App\Entity\Municipios:
  attributes:
    id:
      groups: ['municipio', 'create_direccion', 'get_provincias', 'get_restaurante', 'filtered']

    municipio:
      groups: [ 'municipio', 'create_direccion', 'get_provincias', 'get_restaurante', 'filtered' ]
