App\Entity\Provincias:
  attributes:
    id:
      groups: ['get_direccion', 'create_direccion', 'get_provincias']

    provincia:
      groups: [ 'get_direccion', 'create_direccion', 'get_provincias' ]