App\Entity\Cliente:
  properties:
    nombre:
      - NotBlank:
          message: 'The name cannot be null or empty.'
      - Type: string

    apellidos:
      - NotBlank:
          message: 'The last name cannot be null or empty.'
      - Type: string

    telefono:
      - NotBlank:
          message: 'The number phone cannot be null or empty.'
      - Regex:
          pattern: '/^^0-9]+$/i'
          match: false
          message : 'Number correct'
      - Length:
          max: 9
          maxMessage: 'The phone no valid'
          min: 9
          minMessage: 'The phone no valid'